import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — PROTEUS",
  description: "How PROTEUS collects, uses, and protects your personal data.",
};

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "48px 24px 80px" }}>
        <a href="/" style={{ display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "13px", color: "var(--text-soft)", textDecoration: "none", marginBottom: "32px", fontFamily: "var(--font-sans)" }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
          Back to PROTEUS
        </a>

        <h1 style={{ fontFamily: "var(--font-display)", fontWeight: 600, fontSize: "clamp(28px, 5vw, 36px)", color: "var(--text)", marginBottom: "12px" }}>Privacy Policy</h1>
        <p style={{ fontSize: "13px", color: "var(--text-faint)", marginBottom: "40px", fontFamily: "var(--font-mono)" }}>Last updated: July 14, 2026</p>

        <div style={{ fontSize: "14.5px", color: "var(--text-soft)", lineHeight: 1.8, fontFamily: "var(--font-sans)" }}>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>1. Data We Collect</h2>
            <p style={{ marginBottom: "12px" }}>We collect the following types of information:</p>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Account data:</strong> Name, email address, and hashed password (if you register with email). OAuth profile data (name, email, image) if you sign in with Google or GitHub.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Uploaded content:</strong> Resumes (PDF/DOCX) and job descriptions you submit for analysis.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Analysis results:</strong> Match scores, gap analyses, rewrite suggestions, and cover letters generated by the Service.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Usage data:</strong> Number of analyses performed, timestamps, and basic interaction patterns.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Technical data:</strong> IP address, browser type, device information, and error logs.</li>
            </ul>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>2. How We Use Your Data</h2>
            <p style={{ marginBottom: "12px" }}>We use your data to:</p>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "6px" }}>Provide and operate the resume analysis Service</li>
              <li style={{ marginBottom: "6px" }}>Authenticate your account and prevent fraud</li>
              <li style={{ marginBottom: "6px" }}>Enforce rate limits and fair usage</li>
              <li style={{ marginBottom: "6px" }}>Send transactional emails (magic links, password resets, analysis completion notifications)</li>
              <li style={{ marginBottom: "6px" }}>Improve the Service and fix bugs</li>
              <li style={{ marginBottom: "6px" }}>Comply with legal obligations</li>
            </ul>
            <p style={{ marginTop: "12px" }}>
              We do <strong style={{ color: "var(--text)" }}>not</strong> use your uploaded content to train AI models. Your resumes and job descriptions are processed ephemerally and are not stored longer than necessary to provide the Service.
            </p>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>3. Third-Party Services</h2>
            <p style={{ marginBottom: "12px" }}>PROTEUS uses the following third-party processors:</p>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Vercel:</strong> Hosting and deployment platform. See <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" style={{ color: "var(--color-gold)", textDecoration: "none" }}>Vercel&apos;s Privacy Policy</a>.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>NVIDIA NIM API:</strong> AI inference for resume analysis. Uploaded content is sent to NVIDIA for processing and is not retained beyond the inference request.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Turso / libSQL:</strong> Database hosting for account data and analysis history.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Resend:</strong> Transactional email delivery (magic links, notifications).</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Google / GitHub:</strong> OAuth authentication (optional, if you choose to sign in this way).</li>
            </ul>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>4. Data Retention</h2>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Account data:</strong> Retained until you delete your account.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Analysis history:</strong> Retained as long as your account is active. You may delete individual analyses at any time.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Uploaded files:</strong> Processed in memory and not permanently stored. Temporarily cached during analysis, then discarded.</li>
              <li style={{ marginBottom: "8px" }}><strong style={{ color: "var(--text)" }}>Sessions:</strong> Expire after 30 days of inactivity.</li>
            </ul>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>5. Data Security</h2>
            <p style={{ marginBottom: "12px" }}>
              We implement industry-standard security measures:
            </p>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "6px" }}>Passwords are hashed with bcrypt (12 rounds)</li>
              <li style={{ marginBottom: "6px" }}>All traffic is encrypted via TLS/HTTPS</li>
              <li style={{ marginBottom: "6px" }}>API keys and secrets are stored as encrypted environment variables</li>
              <li style={{ marginBottom: "6px" }}>Input validation and parameterized queries prevent SQL injection</li>
            </ul>
            <p style={{ marginTop: "12px" }}>
              No method of transmission or storage is 100% secure. While we strive to protect your data, we cannot guarantee absolute security.
            </p>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>6. Your Rights</h2>
            <p style={{ marginBottom: "12px" }}>Depending on your jurisdiction, you may have the right to:</p>
            <ul style={{ paddingLeft: "20px" }}>
              <li style={{ marginBottom: "6px" }}><strong style={{ color: "var(--text)" }}>Access</strong> — Request a copy of the personal data we hold about you</li>
              <li style={{ marginBottom: "6px" }}><strong style={{ color: "var(--text)" }}>Rectification</strong> — Request correction of inaccurate data</li>
              <li style={{ marginBottom: "6px" }}><strong style={{ color: "var(--text)" }}>Deletion</strong> — Request deletion of your account and all associated data</li>
              <li style={{ marginBottom: "6px" }}><strong style={{ color: "var(--text)" }}>Portability</strong> — Request your data in a machine-readable format</li>
              <li style={{ marginBottom: "6px" }}><strong style={{ color: "var(--text)" }}>Objection</strong> — Object to processing of your personal data</li>
            </ul>
            <p style={{ marginTop: "12px" }}>
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:deshmukhdaniel2005@gmail.com" style={{ color: "var(--color-gold)", textDecoration: "none" }}>deshmukhdaniel2005@gmail.com</a>.
            </p>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>7. Children&apos;s Privacy</h2>
            <p>
              PROTEUS is not intended for users under the age of 13. We do not knowingly collect data from children. If we learn that a child under 13 has provided personal information, we will delete it promptly.
            </p>
          </section>

          <section style={{ marginBottom: "36px" }}>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>8. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to changes. Material changes will be communicated via email or a notice on the Service. Continued use after changes are posted constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: "var(--font-display)", fontSize: "20px", fontWeight: 600, color: "var(--text)", marginBottom: "14px" }}>9. Contact</h2>
            <p>
              For privacy-related inquiries, contact us at{" "}
              <a href="mailto:deshmukhdaniel2005@gmail.com" style={{ color: "var(--color-gold)", textDecoration: "none" }}>deshmukhdaniel2005@gmail.com</a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
