"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: "60px 65px",
    fontSize: 11,
    lineHeight: 1.6,
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 32,
    borderBottomWidth: 1,
    borderBottomColor: "#c9a962",
    paddingBottom: 22,
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  role: {
    fontSize: 11,
    color: "#c9a962",
    fontWeight: "bold",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  date: {
    fontSize: 10,
    color: "#888",
    marginBottom: 28,
    textAlign: "right",
  },
  body: {
    fontSize: 11,
    lineHeight: 1.7,
    color: "#333",
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 65,
    right: 65,
    fontSize: 8,
    color: "#aaa",
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#ddd",
    paddingTop: 10,
  },
});

export interface CoverLetterData {
  content: string;
  candidateName?: string;
  role?: string;
  date?: string;
}

export function CoverLetterPDF({ data }: { data: CoverLetterData }) {
  const name = data.candidateName || "Daniel Deshmukh";
  const role = data.role || "Software Engineer";
  const date = data.date || new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // The LLM content already contains greeting, body, and closing.
  // We just render it as-is with proper spacing.
  const paragraphs = data.content
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 5);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header — name + role only, no email */}
        <View style={styles.header}>
          <Text style={styles.name}>{name}</Text>
          <Text style={styles.role}>{role}</Text>
        </View>

        {/* Date */}
        <Text style={styles.date}>{date}</Text>

        {/* Body — LLM content (greeting, paragraphs, closing) */}
        <Text style={styles.body}>
          {paragraphs.join("\n\n")}
        </Text>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by PROTEUS - AI-Powered Resume Analyzer
        </Text>
      </Page>
    </Document>
  );
}
