"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: "60px 65px",
    fontSize: 11,
    lineHeight: 1.6,
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 32,
    borderBottomWidth: 1,
    borderBottomColor: "#c9a962",
    paddingBottom: 22,
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  role: {
    fontSize: 11,
    color: "#c9a962",
    fontWeight: "bold",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  contact: {
    fontSize: 9,
    color: "#666",
    lineHeight: 1.5,
  },
  contactLine: {
    marginBottom: 2,
  },
  date: {
    fontSize: 10,
    color: "#888",
    marginBottom: 28,
    textAlign: "right",
  },
  greeting: {
    fontSize: 11,
    marginBottom: 18,
    color: "#333",
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.7,
    color: "#333",
    marginBottom: 16,
  },
  closing: {
    fontSize: 11,
    marginTop: 28,
    marginBottom: 6,
    color: "#333",
  },
  signature: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginTop: 32,
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 65,
    right: 65,
    fontSize: 8,
    color: "#aaa",
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#ddd",
    paddingTop: 10,
  },
});

export interface CoverLetterData {
  paragraphs: string[];
  candidateName?: string;
  role?: string;
  date?: string;
}

export function CoverLetterPDF({ data }: { data: CoverLetterData }) {
  const name = data.candidateName || "Daniel Deshmukh";
  const role = data.role || "Software Engineer";
  const date = data.date || new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{name}</Text>
          <Text style={styles.role}>{role}</Text>
          <View style={styles.contactLine}>
            <Text style={styles.contact}>danieldeshmukh.dev@gmail.com</Text>
          </View>
          <View style={styles.contactLine}>
            <Text style={styles.contact}>github.com/DanielDeshmukh</Text>
          </View>
        </View>

        {/* Date */}
        <Text style={styles.date}>{date}</Text>

        {/* Greeting */}
        <Text style={styles.greeting}>Dear Hiring Manager,</Text>

        {/* Body paragraphs */}
        {data.paragraphs.map((para, i) => (
          <Text key={i} style={styles.paragraph}>
            {para}
          </Text>
        ))}

        {/* Closing */}
        <Text style={styles.closing}>
          Thank you for considering my application. I look forward to the
          opportunity to contribute to your team.
        </Text>

        <Text style={styles.signature}>{name}</Text>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by PROTEUS - AI-Powered Resume Analyzer
        </Text>
      </Page>
    </Document>
  );
}
