"use client";

import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// Register fonts
Font.register({
  family: "Inter",
  fonts: [
    { src: "https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfAZ9hjQ.woff2", fontWeight: 400 },
    { src: "https://fonts.gstatic.com/s/inter/v18/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuI6fAZ9hjQ.woff2", fontWeight: 600 },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: "60px 65px",
    fontFamily: "Inter",
    fontSize: 11,
    lineHeight: 1.6,
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: "#c9a962",
    paddingBottom: 20,
  },
  name: {
    fontSize: 22,
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  role: {
    fontSize: 12,
    color: "#c9a962",
    fontWeight: 600,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  contact: {
    fontSize: 9,
    color: "#666",
    lineHeight: 1.4,
  },
  date: {
    fontSize: 10,
    color: "#888",
    marginBottom: 24,
    textAlign: "right",
  },
  greeting: {
    fontSize: 11,
    marginBottom: 14,
    color: "#333",
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.65,
    color: "#333",
    marginBottom: 12,
    textAlign: "justify",
  },
  closing: {
    fontSize: 11,
    marginTop: 24,
    color: "#333",
  },
  signature: {
    fontSize: 11,
    fontWeight: 600,
    color: "#1a1a1a",
    marginTop: 30,
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 65,
    right: 65,
    fontSize: 8,
    color: "#aaa",
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#ddd",
    paddingTop: 10,
  },
});

export interface CoverLetterData {
  paragraphs: string[];
  candidateName?: string;
  role?: string;
  date?: string;
}

export function CoverLetterPDF({ data }: { data: CoverLetterData }) {
  const name = data.candidateName || "Daniel Deshmukh";
  const role = data.role || "Software Engineer";
  const date = data.date || new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{name}</Text>
          <Text style={styles.role}>{role}</Text>
          <Text style={styles.contact}>
            danieldeshmukh.dev@gmail.com • github.com/DanielDeshmukh
          </Text>
        </View>

        {/* Date */}
        <Text style={styles.date}>{date}</Text>

        {/* Greeting */}
        <Text style={styles.greeting}>Dear Hiring Manager,</Text>

        {/* Body paragraphs */}
        {data.paragraphs.map((para, i) => (
          <Text key={i} style={styles.paragraph}>
            {para}
          </Text>
        ))}

        {/* Closing */}
        <Text style={styles.closing}>
          Thank you for considering my application. I look forward to the
          opportunity to contribute to your team.
        </Text>

        <Text style={styles.signature}>{name}</Text>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by PROTEUS — AI-Powered Resume Analyzer
        </Text>
      </Page>
    </Document>
  );
}
