"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: "50px 55px",
    fontSize: 10,
    lineHeight: 1.55,
    color: "#1a1a1a",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#c9a962",
  },
  text: {
    fontSize: 10,
    lineHeight: 1.55,
    color: "#333",
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 55,
    right: 55,
    fontSize: 8,
    color: "#aaa",
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#ddd",
    paddingTop: 10,
  },
});

export interface TextDocumentData {
  title: string;
  content: string;
}

export function TextDocumentPDF({ data }: { data: TextDocumentData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{data.title}</Text>
        <Text style={styles.text}>{data.content}</Text>
        <Text style={styles.footer}>
          Generated by PROTEUS - AI-Powered Resume Analyzer
        </Text>
      </Page>
    </Document>
  );
}
